Repository ScilifelabDataCentre/dds_cli, pull requests merged in 2022-02, with the labels that each got.

#234 Add changelog
  CHANGELOG.md
Labels: documentation

#238 Change some outputs to stdout
  dds_cli/__main__.py
  dds_cli/account_manager.py
  dds_cli/base.py
  dds_cli/cli_decorators.py
  dds_cli/data_remover.py
  dds_cli/project_status.py
Labels: cli, should have

#237 Change log and printout info after delivery
  CHANGELOG.md
  dds_cli/base.py
  dds_cli/custom_decorators.py
  dds_cli/data_getter.py
  dds_cli/data_putter.py
  dds_cli/data_remover.py
  dds_cli/file_handler.py
  docs/dds_cli.rst
Labels: cli, must have

#241 moved pull request template from workflow
  .github/pull_request_template.md
Labels: should have

#236 dds project access fix
  CHANGELOG.md
  dds_cli/__init__.py
  dds_cli/__main__.py
  dds_cli/account_manager.py
Labels: must have

#246 change to non-sensitive
  CHANGELOG.md
  dds_cli/__main__.py
  dds_cli/project_creator.py
Labels: should have

#255 Print error message
  dds_cli/project_creator.py
Labels: bug, cli, should have

#252 Update docs
  CHANGELOG.md
  dds_cli/__main__.py
  docs/auth.rst
  docs/conf.py
  docs/data.rst
  docs/dds_cli.rst
  docs/index.rst
  docs/ls.rst
  docs/main.rst
  docs/modules.rst
  docs/project.rst
  docs/usage.rst
  docs/user.rst
  docs/web.rst
  docs/windows.rst
Labels: documentation

#257 Pre-testing version of the CLI
  .github/pull_request_template.md
  .github/workflows/deploy-workflow.yml
  .github/workflows/python-app.yml
  .gitignore
  CHANGELOG.md
  README.md
  dds_cli/__init__.py
  dds_cli/__main__.py
  dds_cli/account_manager.py
  dds_cli/auth.py
  dds_cli/base.py
  dds_cli/custom_decorators.py
  dds_cli/data_getter.py
  dds_cli/data_lister.py
  dds_cli/data_putter.py
  dds_cli/data_remover.py
  dds_cli/directory.py
  dds_cli/exceptions.py
  dds_cli/file_compressor.py
  dds_cli/file_encryptor.py
  dds_cli/file_handler.py
  dds_cli/file_handler_local.py
  dds_cli/file_handler_remote.py
  dds_cli/options.py
  dds_cli/project_creator.py
  dds_cli/project_status.py
  dds_cli/s3_connector.py
  dds_cli/status.py
  dds_cli/text_handler.py
  dds_cli/timestamp.py
  dds_cli/user.py
  dds_cli/utils.py
  demo/creds_get.json
  demo/creds_put.json
  docs/Makefile
  docs/_static/custom.css
  docs/auth.rst
  docs/conf.py
  docs/data.rst
  docs/index.rst
  docs/ls.rst
  docs/main.rst
  docs/make.bat
  docs/project.rst
  docs/source/cli.rst
  docs/source/delivery.rst
  docs/source/excep.rst
  docs/source/files.rst
  docs/source/index.rst
  docs/user.rst
  docs/web.rst
  docs/windows.rst
  requirements.txt
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/test_add_user.py
  tests/test_list.py
  tests/test_utils.py
Labels: must have

#258 version
  setup.py
Labels: must have

#261 added unit and changed url
  CHANGELOG.md
  dds_cli/__init__.py
  dds_cli/__main__.py
  dds_cli/account_manager.py
  tests/test_add_user.py
Labels: must have

#262 Bug fix and change of remote url
  CHANGELOG.md
  dds_cli/__init__.py
  dds_cli/__main__.py
  dds_cli/account_manager.py
  tests/test_add_user.py
Labels: must have

#263 New version
  setup.py
Labels: must have

#264 New version to test PyPi publish
  setup.py
Labels: must have

#265 getting up to speed with the weird versions
  setup.py
Labels: tests, must have

#266 version change
  setup.py
Labels: must have

#267 Version change - remove dev from end
  setup.py
Labels: must have

#268 New version, hopefully last before testing
  setup.py
Labels: must have

#269 new version and updated readme
  README.md
  setup.py
Labels: must have

#270 Incorrect information in readme
  README.md
  setup.py
Labels: cli, must have

#272 Freeze requirements for working setup
  requirements.txt
Labels: must have

#273 Pip freeze
  requirements.txt
Labels: must have

#274 change in version
  .github/pull_request_template.md
  setup.py
Labels: must have

#275 Merge new version and additional step for master PR
  .github/pull_request_template.md
  setup.py
Labels: must have

#276 Update docs
  CHANGELOG.md
  README.md
  dds_cli/__init__.py
  docs/index.rst
  docs/web.rst
  docs/windows.rst
  setup.py
Labels: must have

#277 Update docs and readme
  CHANGELOG.md
  README.md
  dds_cli/__init__.py
  docs/index.rst
  docs/web.rst
  docs/windows.rst
  setup.py
Labels: documentation, must have

#278 Readme was incorrect
  README.md
Labels: must have

#279 add pypi link
  docs/index.rst
Labels: documentation, should have

#280 Update docs
  docs/index.rst
  docs/web.rst
Labels: documentation

#281 Update incorrect docs
  README.md
  docs/index.rst
  docs/web.rst
Labels: documentation

#282 Add pdf to repo
  .gitignore
  docs/_build/latex/datadeliverysystem.pdf
Labels: documentation

#283 Add test protocol / docs to repo
  .gitignore
  docs/_build/latex/datadeliverysystem.pdf
Labels: documentation

#284 pandas and numpy removed
  requirements.txt
Labels: should have

#288 Unfreeze
  CHANGELOG.md
  requirements.txt
Labels: should have
