Repository ScilifelabDataCentre/dds_cli, pull requests merged in 2022-04, with the labels that each got.

#446 Project Access Fix Message
  CHANGELOG.md
  dds_cli/account_manager.py
Labels: must have

#449 Add MOTD command
  CHANGELOG.md
  dds_cli/__init__.py
  dds_cli/__main__.py
  dds_cli/motd_manager.py
Labels: should have

#450 Add docstring about "Please reauth" before delivery to avoid delivery being cancelled
  CHANGELOG.md
  dds_cli/__main__.py
Labels: must have

#451 Change json response
  dds_cli/project_creator.py
Labels: should have

#452 Better error message if there are no unit users
  dds_cli/account_manager.py
  dds_cli/utils.py
Labels: bug, must have

#453 remove 'currently minimal'
  docs/index.rst
Labels: documentation, should have

#454 Before release 1.0.1
  .github/workflows/codeql-analysis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  dds_cli/__init__.py
  dds_cli/__main__.py
  dds_cli/account_manager.py
  dds_cli/motd_manager.py
  dds_cli/project_creator.py
  dds_cli/utils.py
  dds_cli/version.py
  docs/index.rst
Labels: must have

#456 Documentation bug
  docs/conf.py
Labels: bug, documentation, must have

#457 Change to make clean
  .github/workflows/deploy-workflow.yml
  dds_cli/version.py
Labels: must have

#458 Update deploy-ghp.yml
  .github/workflows/deploy-ghp.yml
Labels: must have

#459 Update version.py
  dds_cli/version.py
Labels: must have

#461 Pin versions
  CHANGELOG.md
  requirements-dev.txt
Labels: documentation, must have

#469 Remove complicated tests
  CHANGELOG.md
  tests/conftest.py
  tests/requirements-test.txt
  tests/test_add_user.py
  tests/test_empty.py
  tests/test_list.py
  tests/test_utils.py
Labels: tests
