Repository ScilifelabDataCentre/dds_cli, pull requests merged in 2022-03, with the labels that each got.

#289 Remove pinned versions of packages
  CHANGELOG.md
  requirements.txt
  setup.py
Labels: should have

#299 Update show-history option
  dds_cli/__main__.py
Labels: should have

#298 Remove message duplication
  dds_cli/__main__.py
  dds_cli/auth.py
Labels: should have

#296 Print error message
  dds_cli/project_creator.py
Labels: must have

#302 change previous merged PR after finding duplicate
  dds_cli/__main__.py
  dds_cli/auth.py
Labels: bug, should have

#304 bump version
  setup.py
Labels: must have

#306 unused boolean return
  dds_cli/auth.py
Labels: should have

#307 update docs with comments from testing
  docs/auth.rst
  docs/project.rst
  docs/user.rst
  docs/web.rst
Labels: documentation

#311 pdf after typo
  docs/_build/latex/datadeliverysystem.pdf
Labels: documentation

#308 Updated documentation from testing
  docs/_build/latex/datadeliverysystem.pdf
  docs/auth.rst
  docs/project.rst
  docs/user.rst
  docs/web.rst
Labels: documentation

#314 add windows
  .gitignore
Labels: documentation

#313 Add images for docs
  .gitignore
  CHANGELOG.md
  dds_cli/data_lister.py
  docs/_static/help.png
  docs/_static/hotp.png
  docs/_static/invite.png
  docs/_static/login.png
  docs/_static/password_change.png
  docs/_static/password_change_success.png
  docs/_static/password_forgot.png
  docs/_static/password_forgot_email.png
  docs/_static/password_reset.png
  docs/_static/password_reset_success.png
  docs/_static/registration_completed.png
  docs/_static/registration_researcher.png
  docs/_static/registration_unit.png
  docs/_static/windows/path-0.png
  docs/_static/windows/path-1.png
  docs/_static/windows/path-2.png
  docs/_static/windows/path-4.png
  docs/_static/windows/powershell-4.png
  docs/_static/windows/powershell-9.png
  docs/_static/windows/powershell_top-0.png
  docs/_static/windows/powershell_top-1.png
  docs/_static/windows/powershell_top-10.png
  docs/_static/windows/powershell_top-7.png
  docs/_static/windows/python_exe.png
  docs/_static/windows/python_install-0.png
  docs/_static/windows/python_install-1.png
  docs/_static/windows/python_install-2.png
  docs/_static/windows/python_install-3.png
  docs/_static/windows/python_install-4.png
  docs/_static/windows/python_install-5.png
  docs/_static/windows/python_install.png
  docs/_static/windows/windows_security.png
  requirements-dev.txt
Labels: bug

#326 bump cli version
  setup.py
Labels: must have

#327 Bump rich-click
  CHANGELOG.md
  dds_cli/__main__.py
  requirements.txt
  setup.py
Labels: must have

#334 New `--token-path` option and no `--username`
  CHANGELOG.md
  dds_cli/__main__.py
  dds_cli/account_manager.py
  dds_cli/auth.py
  dds_cli/base.py
  dds_cli/data_getter.py
  dds_cli/data_lister.py
  dds_cli/data_putter.py
  dds_cli/data_remover.py
  dds_cli/options.py
  dds_cli/project_creator.py
  dds_cli/project_status.py
  dds_cli/user.py
  docs/_build/latex/datadeliverysystem.pdf
  docs/auth.rst
  setup.py
  tests/test_add_user.py
Labels: cli

#335 minor change for the cli to work with minio in dev mode
  CHANGELOG.md
  dds_cli/s3_connector.py
Labels: bug

#337 Add support for zero-conf dev environment to the cli
  CHANGELOG.md
  dds_cli/__init__.py
Labels: must have

#352 Fix `dds user delete --self` bug
  dds_cli/account_manager.py
Labels: bug, must have

#353 f string to fix bug
  dds_cli/directory.py
Labels: bug, must have

#358 remove duplicate message after response error
  dds_cli/exceptions.py
Labels: bug, cli, must have

#357 Add confirmation in case of project deletion
  CHANGELOG.md
  dds_cli/__main__.py
  dds_cli/user.py
  dds_cli/utils.py
Labels: enhancement, must have

#360 Changed proceed_deletion check
  dds_cli/__main__.py
  dds_cli/utils.py
Labels: cli, could have

#363 bump version
  setup.py
Labels: must have

#369 Replace the default help messages of Click
  CHANGELOG.md
  dds_cli/__main__.py
Labels: should have

#371 Improve error message when --destination exists
  CHANGELOG.md
  dds_cli/directory.py
Labels: should have

#370 fix error messages
  dds_cli/account_manager.py
Labels: must have

#374 Improved messages, add confirmation prompt and escape characters
  CHANGELOG.md
  dds_cli/__main__.py
  dds_cli/account_manager.py
  dds_cli/auth.py
  dds_cli/custom_decorators.py
  dds_cli/data_getter.py
  dds_cli/data_lister.py
  dds_cli/data_putter.py
  dds_cli/data_remover.py
  dds_cli/directory.py
  dds_cli/file_encryptor.py
  dds_cli/s3_connector.py
  setup.py
  tests/test_list.py
Labels: must have

#379 Fix project access error message
  CHANGELOG.md
  dds_cli/account_manager.py
  dds_cli/exceptions.py
  dds_cli/utils.py
Labels: must have

#384 New `dds user ls` command
  CHANGELOG.md
  dds_cli/__init__.py
  dds_cli/__main__.py
  dds_cli/account_manager.py
  dds_cli/data_lister.py
  dds_cli/utils.py
Labels: must have

#383 Add access column and add check mark or cross
  CHANGELOG.md
  dds_cli/data_lister.py
  dds_cli/utils.py
  tests/test_list.py
Labels: enhancement, must have

#400 Update text
  dds_cli/__main__.py
  dds_cli/user.py
Labels: could have

#401 Authentication text
  dds_cli/auth.py
Labels: should have

#404 changed from aborted command to an abort flag in archiving
  CHANGELOG.md
  dds_cli/__main__.py
Labels: could have

#395 Set file permissions using icacls on Windows, no check
  CHANGELOG.md
  dds_cli/user.py
Labels: bug, must have

#403 Warning and confirmation prompt when creating projects in unit without 3 unit admin
  dds_cli/project_creator.py
Labels: must have

#407 Delete folder
  .github/workflows/python-app.yml
  CHANGELOG.md
  dds_cli/base.py
  dds_cli/data_getter.py
  dds_cli/data_putter.py
  dds_cli/utils.py
  requirements.txt
  tests/requirements-test.txt
  tests/test_utils.py
Labels: should have

#410 Fix size usage cost
  dds_cli/__main__.py
  dds_cli/data_lister.py
  dds_cli/utils.py
Labels: must have

#411 allow delete of both file and folder
  CHANGELOG.md
  dds_cli/__main__.py
Labels: must have

#412 Check if token exists
  dds_cli/user.py
Labels: must have

#399 change to 7 days
  dds_cli/__main__.py
Labels: documentation, must have

#408 Add info about number of deleted files, db delete failure
  CHANGELOG.md
  dds_cli/data_remover.py
Labels: should have

#418 Fix error message
  dds_cli/account_manager.py
Labels: must have

#419 Release actions
  .github/workflows/deploy-workflow.yml
  .github/workflows/make-release.yml
  CHANGELOG.md
  dds_cli/__init__.py
  requirements-dev.txt
  resources/scilifelab.icns
  resources/scilifelab.ico
Labels: must have

#415 remove invite with is-invite option
  CHANGELOG.md
  dds_cli/__main__.py
  dds_cli/account_manager.py
Labels: must have

#426 Handle error log
  CHANGELOG.md
  dds_cli/base.py
  dds_cli/file_handler.py
Labels: must have

#429 Add Linux to deploy-workflow.yml
  .github/workflows/deploy-workflow.yml
Labels: must have

#430 Update docs
  .github/workflows/deploy-workflow.yml
  dds_cli/__main__.py
  dds_cli/auth.py
  dds_cli/data_getter.py
  dds_cli/data_putter.py
  docs/_build/latex/datadeliverysystem.pdf
  docs/index.rst
  setup.py
Labels: documentation, must have

#432 Windows instruction moved to repo and remove testing instructions in docs
  WINDOWS.md
  docs/auth.rst
  docs/data.rst
  docs/index.rst
  docs/ls.rst
  docs/main.rst
  docs/project.rst
  docs/unit.rst
  docs/user.rst
  docs/web.rst
  docs/windows.rst
Labels: documentation, must have

#433 Update docs
  docs/index.rst
  docs/installation.rst
Labels: documentation, must have

#434 Change example in readme
  README.md
Labels: documentation, must have

#435 Update docs according to tester feedback
  dds_cli/__main__.py
  docs/index.rst
Labels: documentation, must have

#436 Deploy documentation to Github pages on push to master
  .github/workflows/deploy-ghp.yml
  CHANGELOG.md
  docs/Makefile
  docs/_static/SciLifeLab_symbol_green.svg
  docs/conf.py
Labels: documentation, must have

#438 Base main connection error
  dds_cli/__main__.py
  dds_cli/base.py
  dds_cli/data_getter.py
  dds_cli/data_lister.py
  dds_cli/data_remover.py
  dds_cli/exceptions.py
  dds_cli/file_handler_local.py
  dds_cli/file_handler_remote.py
  dds_cli/project_creator.py
  dds_cli/project_status.py
  dds_cli/s3_connector.py
  dds_cli/user.py
  dds_cli/utils.py
Labels: must have

#437 catch connectionerror in account manager
  dds_cli/account_manager.py
Labels: must have

#439 Refactor version handling to allow PyInstaller builds
  .github/pull_request_template.md
  .github/workflows/deploy-workflow.yml
  CHANGELOG.md
  dds_cli/__init__.py
  dds_cli/version.py
  setup.py
Labels: must have

#441 Fix bianca docs
  docs/installation.rst
Labels: documentation

#427 Prep before production release
  .github/pull_request_template.md
  .github/workflows/deploy-ghp.yml
  .github/workflows/deploy-workflow.yml
  .github/workflows/python-app.yml
  CHANGELOG.md
  README.md
  WINDOWS.md
  dds_cli/__init__.py
  dds_cli/__main__.py
  dds_cli/account_manager.py
  dds_cli/auth.py
  dds_cli/base.py
  dds_cli/custom_decorators.py
  dds_cli/data_getter.py
  dds_cli/data_lister.py
  dds_cli/data_putter.py
  dds_cli/data_remover.py
  dds_cli/directory.py
  dds_cli/exceptions.py
  dds_cli/file_compressor.py
  dds_cli/file_handler.py
  dds_cli/file_handler_local.py
  dds_cli/file_handler_remote.py
  dds_cli/options.py
  dds_cli/project_creator.py
  dds_cli/project_status.py
  dds_cli/s3_connector.py
  dds_cli/unit_manager.py
  dds_cli/user.py
  dds_cli/utils.py
  dds_cli/version.py
  docs/Makefile
  docs/_build/latex/datadeliverysystem.pdf
  docs/_static/SciLifeLab_symbol_green.svg
  docs/auth.rst
  docs/conf.py
  docs/data.rst
  docs/index.rst
  docs/installation.rst
  docs/ls.rst
  docs/main.rst
  docs/project.rst
  docs/unit.rst
  docs/user.rst
  docs/web.rst
  docs/windows.rst
  requirements-dev.txt
  requirements.txt
  resources/scilifelab.icns
  resources/scilifelab.ico
  setup.py
  tests/requirements-test.txt
  tests/test_list.py
  tests/test_utils.py
Labels: must have

#442 fix invalid characters
  docs/installation.rst
Labels: must have

#443 Fix of docs
  docs/installation.rst
Labels: must have

#444 Instructions on executables
  docs/installation.rst
Labels: documentation, must have

#445 Info on executables in docs
  docs/installation.rst
Labels: documentation, must have
