Repository ScilifelabDataCentre/dds_cli, pull requests merged in 2025-09, with the labels that each got.

#734 Run Pytest on Windows as well
  .github/workflows/pytest-cli.yml
  SPRINTLOG.md
  dds_cli/__init__.py
  dds_cli/dds_gui/dds_state_manager.py
  dds_cli/user.py
  docs/procedures/new_release.md
  gui_build/gui_standalone.py
  tests/gui_tests/test_authentication.py
  tests/gui_tests/test_important_information.py
  tests/test_auth.py
  tests/test_base.py
  tests/test_data_remover.py
  tests/test_file_compressor.py
  tests/test_file_encryptor.py
  tests/test_file_handler_local.py
  tests/test_motd_manager.py
  tests/test_project_status.py
  tests/test_superadmin_helper.py
  tests/test_utils.py
Labels: skip-changelog

#774 Add Dardel section to the documentation
  SPRINTLOG.md
  docs/index.rst
  docs/installation.rst
  docs/procedures/new_release.md
Labels: type: docs

#838 Implement Project Info in GUI
  SPRINTLOG.md
  dds_cli/dds_gui/dds_state_manager.py
  dds_cli/dds_gui/models/project_information.py
  dds_cli/dds_gui/pages/project_information/project_information.py
  dds_cli/dds_gui/pages/project_list/project_list.py
  dds_cli/dds_gui/pages/project_view.py
  tests/gui_tests/test_authentication.py
  tests/gui_tests/test_project_content.py
  tests/gui_tests/test_project_information.py
  tests/gui_tests/test_project_list.py
Labels: type: feature

#839 Fix error handling bug in GUI authentication
  SPRINTLOG.md
  dds_cli/dds_gui/pages/authentication/authentication_form.py
  tests/gui_tests/test_authentication.py
Labels: type: bug

#846 Specify download timeouts to avoid s3 errors
  SPRINTLOG.md
  dds_cli/constants.py
  dds_cli/data_getter.py
  dds_cli/s3_connector.py
  tests/test_data_getter.py
  tests/test_s3_connector.py
Labels: type: feature
