Repository ScilifelabDataCentre/dds_cli, pull requests merged in 2025-08, with the labels that each got.

#768 Corrupt file check - file size check
  dds_cli/data_getter.py
Labels: type: feature

#769 ADR decisions for GUI
  .adr-dir
  SPRINTLOG.md
  docs/architecture/decisions/0001-use-textual-as-gui-framework.md
  docs/architecture/decisions/0002-use-project-centered-layout.md
  docs/architecture/decisions/0003-implement-specific-component-tests.md
Labels: type: docs

#777 Handle KeyboardInterrupt when cancelling file
  SPRINTLOG.md
  dds_cli/custom_decorators.py
Labels: type: bug, codex

#787 test: use dynamic file path in compressor error log
  tests/test_file_compressor.py
Labels: codex

#790 Refactor LocalFileHandler tests to use pathlib paths
  tests/test_file_handler_local.py
Labels: skip-changelog, codex

#791 Normalize path expectations in file compressor tests
  tests/test_file_compressor.py
Labels: skip-changelog, codex

#799 Use explicit home token path
  dds_cli/dds_gui/dds_state_manager.py
Labels: skip-changelog, codex

#798 Use Path for path handling in utils tests
  tests/test_utils.py
Labels: skip-changelog, codex

#794 refactor tests to use Path for token_path
  tests/test_auth.py
  tests/test_base.py
Labels: skip-changelog, codex

#800 Update expanduser to pathlib
  dds_cli/user.py
Labels: codex

#810 test: use log substrings in project status tests
  tests/test_project_status.py
Labels: skip-changelog, codex

#815 test: mock connection error in perform_request
  tests/test_utils.py
Labels: skip-changelog, codex

#816 test: make stats table border check flexible
  tests/test_superadmin_helper.py
Labels: skip-changelog, codex

#822 Remove commitish -- Release Drafter is not picking up changes
  .github/release-drafter.yml
Labels: skip-changelog

#824 New version 2.12.0 and Changelog
  CHANGELOG.rst
  SPRINTLOG.md
  dds_cli/version.py
  img/dds-help-1.svg
  img/dds-help-2.svg
  img/dds-version.svg
  img/python-version.svg
  img/python3-version.svg
Labels: skip-changelog

#827 docs: fix typo in security policy
  SECURITY.md
Labels: skip-changelog, codex

#828 docs: correct user privileges typo in examples
  docs/examples.rst
Labels: skip-changelog, codex

#831 Fix grammar in base class docstring
  dds_cli/base.py
Labels: skip-changelog, codex

#833 Add sprint log update workflow
  .github/workflows/update-sprintlog.yml
Labels: codex
